version: "3.7"
services:

 app:

     build:
      args:
        COMPOSER_ENV : production
      context: ./app
      dockerfile: Dockerfile

     environment:
        - COMPOSER_ENV=production

 nginx:
  volumes:
   - ./app/code:/var/www:ro
   - ./nginx:/etc/nginx/conf.d:ro
  depends_on:
   - app
   - database

 database:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: test